name: Deploy

on:
  push:
#    branches:
#      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@master
      - name: Create identity file
        env:
          KEY: ${{ secrets.KEY }}
        run: |
          echo $KEY > ${HOME}/memebot_api_rsa
          chmod 600 ${HOME}/memebot_api_rsa
      - name: Upload files to memecentral
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
        run: rsync -a --delete --exclude ".git" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${HOME}/memebot_api_rsa" ${GITHUB_WORKSPACE}/ ${USERNAME}@${HOST}:/home/memebot-api/
      - name: Reload PM2 server
        uses: appleboy/ssh-action@master
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MEMEBOT_IP: ${{ secrets.MEMEBOT_IP }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          envs: MONGO_URL,MEMEBOT_IP
          script_stop: true
          script: |
            cd /home/memebot-api/
            nvm install
            yarn
            pm2 startOrReload ecosystem.config.yml
            pm2 save
