name: Deploy

on:
  push:
    branches:
      - master

env:
  HOST: ${{ secrets.HOST }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@master
      - name: Create identity file
        env:
          KEY: ${{ secrets.KEY }}
        run: |
          printf "%s" "$KEY" > "${HOME}/memebot_api_rsa"
          chmod 600 ${HOME}/memebot_api_rsa
      - name: Add secrets to PM2 Config
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MEMEBOT_IP: ${{ secrets.MEMEBOT_IP }}
        run: node ${GITHUB_WORKSPACE}/scripts/pm2-config.js MONGO_URL MEMEBOT_IP
      - name: Upload files to memecentral
        run: rsync -a --delete --exclude ".git" -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${HOME}/memebot_api_rsa" ${GITHUB_WORKSPACE}/ ${USERNAME}@${HOST}:~/memebot-api/
      - name: Reload PM2 server
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ${HOME}/memebot_api_rsa ${USERNAME}@${HOST} -T << EOF
            MONGO_URL="${MONGO_URL}"
            MEMEBOT_IP="${MEMEBOT_IP}"
            cd ~/memebot-api/
            nvm install
            yarn
            pm2 startOrReload ecosystem.config.json
            pm2 save
          EOF
