name: CI

on:
  push:
    branches: 
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Upload files to server
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.KEY }}
      with:
        source: "."
        target: "/home/memebot"
    - name: Build and deploy server
      uses: appleboy/ssh-action@master
      env:
        MONGO_URL: ${{ secrets.MONGO_URL }}
        NODE_ENV: production
        MEME_DIR: ./.memes
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        env: MONGO_URL, NODE_ENV, MEME_DIR
        script_stop: true
        script: |
          cd /home/memebot/
          nvm install
          yarn
          yarn serve
